# -*- coding: utf-8 -*-
"""Gestionador_ventas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apVMQi2itDsqoqdMpfWh2BNSN2LIEc2d
"""

#CARLOS DE FERRARI --------> ATCARIUS
import time
import numpy as np 
Ruts=[]
Nombres=[]
Edades=[]
Panes=[]
Bebidas=[]
Frutas=[]
totalFinal = 0 
descuento = 0
suma = 0
tipo=None
flag=True
totalproductos=[]
totaltotal=[]

print("Bienvenido al Gestionador de ventas de Carlitos!")
print()
while flag:
    menu1=int(input("Seleccione un menú \n1.-Ingresar datos para clientes \n2.-Mostrar datos guardados \n3.-Editar datos guardados de clientes \n4.-Eliminar datos de clientes\n5.-Salir\n"))
    while menu1<1 or menu1>5: 
      print("Ingrese una opción válida (1-5)\n")
      menu1=int(input("Seleccione un menú \n1.-Ingresar datos para clientes \n2.-Mostrar datos guardados \n3.-Editar datos guardados de clientes \n4.-Eliminar datos de clientes\n5.-Salir\n"))

    while menu1==1 or menu1==2 or menu1==3 or menu1==4 or menu1==5:
      if menu1==1: #MENU INGRESO DE DATOS DEL CLIENTE
        rut=int(input("Ingrese su rut sin digito verificador ni punto: "))
        while rut <=4000000 or rut>=99999999:
          print()
          print("Ingrese un rut válido")
          rut=int(input("Ingrese su rut sin digito verificador ni punto: "))
        
        Ruts.append(rut)
        nombre=input("Ingrese su nombre completo: ")
        Nombres.append(nombre)

        edad=int(input("Ingrese su edad: "))
        while edad<=0 or edad>=110:
          print()
          print("Ingrese una edad válida")
          edad=int(input("Ingrese su edad: "))
          edad.append(Edades)
            
        cantidadPanes = int(input("ingrese cantidad de Pan: "))
        totalPan = cantidadPanes * 1000
        totalFinal = totalFinal + totalPan
        Panes.append(cantidadPanes)
        print(f"EL TOTAL A PAGAR ES ${totalFinal}")

        cantidadFrutas =  int(input("ingrese cantidad de Frutas: "))
        totalFruta= cantidadFrutas * 500
        totalFinal = totalFinal + totalFruta
        Frutas.append(cantidadFrutas)
        print(f"EL TOTAL A PAGAR ES ${totalFinal}")

        cantidadBebidas =  int(input("ingrese cantidad de Bebidas: "))
        totalBebidas= cantidadBebidas * 1300
        totalFinal = totalFinal + totalBebidas
        Bebidas.append(cantidadBebidas)
        print(f"EL TOTAL A PAGAR ES ${totalFinal}")
        totaltotal.append(totalFinal)
          
        productos = cantidadBebidas + cantidadPanes + cantidadFrutas
        totalproductos.append(productos)


        if totalFinal>3000:
          totalFinal = totalFinal * 0.90
          print(f"DEBIDO A QUE SU TOTAL SUPERA LOS $3.000 HA OBTENIDO UN DESCUENTO DE 10% POR LO QUE SU NUEVO TOTAL A PAGAR ES ${totalFinal}")

        efectivo = int(input("ingrese efectivo a pagar: "))
        if efectivo<totalFinal:
          efectivo = int(input("Su monto es insuficiente,ingrese un monto mayor al total PorFavor: "))
        elif efectivo>= totalFinal:
          vuelto = efectivo - totalFinal
          print(f"su vuelto es de  ${vuelto}")
          print("Muchas gracias por la compra, sus datos se han guardado")
          break

      if menu1==2: #VER DATOS DE CLIENTE
          print()
          print("-"*30)
          print()
          print("Menú para ver datos del cliente")
          print()
          print("Tenemos los siguientes RUT de clientes guardados:",Ruts)
          print("Siguientes nombres",Nombres)
          print("Panes comprandos:",Panes)
          print("Frutas compradas:",Frutas)
          print("Bebidas compradas:",Bebidas)
          print("El total de productos comprados por el cliente fue:")
          print(totalproductos)
          print("Total de su ultima venta:",totalFinal)
          if totalFinal>3000:
            totalFinal = totalFinal/0.90/10
            print(f"Su descuento fue de ${totalFinal}")
          else:
            print("Debido a que el valor de su compra fue por debajo de los $3.000 usted no ha obtenido descuento.")
          break
          print("El cliente pago en efectivo la suma de",efectivo)
          print("El vuelto de su ultima compra fue:",vuelto)
      
      
      if menu1 == 3: #BORRAR DATOS DE CLIENTE
        print("Porfavor Seleccione que apartado desea modificar")
        print("-"*35)
        print("\n0.-RUT del cliente\n1.-Nombre del cliente\n2.-Panes comprados por el cliente\n3.-Frutas compradas por el cliente\n4.-Bebidas compradas por el cliente")
        opcmod=int(input("Seleccione una opcion"))
        if opcmod==0:
          print(Ruts)
          print("Ingrese el numero de rut a modificar,El primero es el numero '0' y asi sucesivamente.")
          i = int(input())
          print("Ingrese un nuevo valor")
          val = input()
          (Ruts)[i] = val
          print("La lista ha sido actualizada")
          print("-"*45)
          print(Ruts)
          break
        if opcmod==1:
          print(Nombres)
          print("Ingrese el numero del nombre a modificar,El primero es el numero '0' y asi sucesivamente.")
          i = int(input())
          print("Ingrese un nuevo valor")
          val = input()
          (Nombres)[i] = val
          print("La lista ha sido actualizada")
          print("-"*45)
          print(Nombres)
          break
        if opcmod==2:
          print(Panes)
          print("Ingrese el numero del apartado de panes a modificar,El primero es el numero '0' y asi sucesivamente.")
          i = int(input())
          print("Ingrese un nuevo valor")
          val = input()
          (Panes)[i] = val
          print("La lista ha sido actualizada")
          print("-"*45)
          print(Panes)
          break
        if opcmod==3:
          print(Frutas)
          print("Ingrese el numero del apartado de frutas a modificar,El primero es el numero '0' y asi sucesivamente.")
          i = int(input())
          print("Ingrese un nuevo valor")
          val = input()
          (Frutas)[i] = val
          print("La lista ha sido actualizada")
          print("-"*45)
          print(Frutas)
          break 
        if opcmod==4:
          print(Bebidas)
          print("Ingrese el numero del apartado de bebidas a modificar,El primero es el numero '0' y asi sucesivamente.")
          i = int(input())
          print("Ingrese un nuevo valor")
          val = input()
          (Bebidas)[i] = val
          print("La lista ha sido actualizada")
          print("-"*45)
          print(Bebidas)
          break 

      if menu1==4: #BORRAR DATOS DE CLIENTE
        print("Indique por favor si desea borrar los datos de todos los clientes o solo de uno: ")
        opcmod2=int(input("\n1.-Borrar todo\n2.-Borrar los datos de un cliente en especifico"))
        if opcmod2 == 1:
            Nombres.clear()
            Ruts.clear()
            Edades.clear()
            Panes.clear()
            Frutas.clear()
            Bebidas.clear()
            print("\nLos datos de los clientes se han borrado con éxito\n")
            time.sleep(3)
            print("-"*30)
            print()
            break
        if opcmod == 2:
          print("Indique que le gustaria borrar especificamente: ")
          print("\n1.-Un nombre\n2.-Un rut\n3.-Una edad\n4.-Una cantidad de panes\n5.-Una cantidad de frutas\n6.-Una cantidad de bebidas")
          opcmod3=int(input("Elija una opcion: "))
          
          if opcmod3 ==1:
            print(Nombres)
            print("Ingrese el numero del nombre a eliminar,El primero es el numero '0' y asi sucesivamente.")
            i = int(input())
            Nombres.pop(i)
            print("La lista ha sido actualizada")
            print("-"*45)
            print(Nombres)
            break
          if opcmod3 ==2:
            print(Ruts)
            print("Ingrese el numero del Rut a eliminar,El primero es el numero '0' y asi sucesivamente.")
            i = int(input())
            Ruts.pop(i)
            print("La lista ha sido actualizada")
            print("-"*45)
            print(Ruts)
            break
          if opcmod3 ==3:
            print(Edades)
            print("Ingrese el numero de la edad a eliminar,La primera es la numero '0' y asi sucesivamente.")
            i = int(input())
            Edades.pop(i)
            print("La lista ha sido actualizada")
            print("-"*45)
            print(Edades)
            break
          if opcmod3 ==4:
            print(Panes)
            print("Ingrese el numero de Panes a eliminar,El primero es el numero '0' y asi sucesivamente.")
            i = int(input())
            Panes.pop(i)
            print("La lista ha sido actualizada")
            print("-"*45)
            print(Panes)
            break
          if opcmod3 ==5:
            print(Frutas)
            print("Ingrese el elemento con el numero de frutas a eliminar,El primero es el numero '0' y asi sucesivamente.")
            i = int(input())
            Frutas.pop(i)
            print("La lista ha sido actualizada")
            print("-"*45)
            print(Frutas)
            break
          if opcmod3 ==6:
            print(Bebidas)
            print("Ingrese el elemento con el numero de bebidas a eliminar,El primero es el numero '0' y asi sucesivamente.")
            i = int(input())
            Bebidas.pop(i)
            print("La lista ha sido actualizada")
            print("-"*45)
            print(Bebidas)
            break


      while menu1==5: #MENU SALIR
        print()
        print("¡Hasta pronto!")
        print("-"*30)
        menu1=0
        flag=False